### PR TITLE
You can use override to specify material XP rate.

### PR DESCRIPTION
**Pull request by talonos2**
Added to levelling logic: Each material now has an XP multiplier, so you
can make some materials level up faster than others. Each material
defaults to 100% normal experience, but can be changed in the material
override module.

You might ask who would ever use this function. I plan on using it in my
upcoming modpack, so there's one interested party, at least. :/

### CODE REVIEW

**Comment by bonii-xx** [comment]
I wish I would get notifications when a PR changes >:(
*takes a look*

**Comment by bonii-xx** [comment]
Ok, I'm gonna pull that in, but if it causes errors or other problems you'll have to fix them or I'm going to throw it out again. ;)

**Comment by talonos2** [comment]
You've got a deal. 100%.

**Comment by bonii-xx** [comment]
The implementation looks quite save though, so I don't think it'll cause much trouble.

**Pull request merged**
