### PR TITLE
Add fr_FR to your mod ;)

### PR DESCRIPTION
**Pull request by Maxwelljones**
Translated to french (mothertongue).
Hope it's useful.
Not sure if this is the right way to do it as Im quite new to GitHub...

### CODE REVIEW

**Comment by bonii-xx** [comment]
It is, uh, semi right. You killed the original english localization. But I can fix it.

**Comment by Maxwelljones** [comment]
huh.. sorry! What did i do wrong?
Forking, then I need to create a new copy for the translation?

**Comment by bonii-xx** [comment]
As I said, you deleted the english localization. But I merged it in indirectly.
https://github.com/SlimeKnights/IguanaTweaksTConstruct/commit/fd138eafeb6df1aaff84c11dbc49819d69369e63

**Comment by Maxwelljones** [comment]
All right!
Thanks =) I got the point. so there's no need to fork? I could just create a new file in the project?

**Comment by bonii-xx** [comment]
No, you have to fork and then create a PR. But you deleted the en_US.lang file.

**Comment by Maxwelljones** [comment]
Ok I get it. Thanks for implementing and for taking the time to answer. I'll do better next time!

**Pull request closed without merging**
