### PR TITLE
Create ko_KR.lang

### PR DESCRIPTION
**Pull request by nark31**
'Bat Hat' is 'BatMan Mask'? or Just Hat?

Skill level desc add an arbitrarily possible?
ex.) tooltip.level.skill.74=세렌

### CODE REVIEW

**Comment by bonii-xx** [comment]
Up to you @mask

Sure we can add a skill level like that, but why Serendipity?

**Comment by nark31** [comment]
* Translation BatHat, Desc

No reason, He is korean mod informaion poster. I think the best of his post. http://digestivo.tistory.com/

**Comment by bonii-xx** [comment]
Cool. Then you can add it, was just surprised because there have been some problems with serendipitymc and wanted to make sure it's not connected.

**Comment by nark31** [comment]
Thank you for your kindness. :)

**Pull request merged**
